dockerfile: Add also missing license file
One more build error to handle:
2.489 Downloading numpy (17.8MiB)
2.492 Downloading pygments (1.2MiB)
6.075   × Failed to build `netflix-oca-locator @ file:///app`
6.075   ├─▶ The build backend returned an error
6.075   ╰─▶ Call to `hatchling.build.build_editable` failed (exit status: 1)
6.075
6.075       [stderr]
6.075       Traceback (most recent call last):
6.075         File "<string>", line 11, in <module>
6.075         File
6.075       "/root/.cache/uv/builds-v0/.tmpq7epIe/lib/python3.11/site-packages/hatchling/build.py",
6.075       line 83, in build_editable
6.075           return os.path.basename(next(builder.build(directory=wheel_directory,
6.075       versions=["editable"])))
6.075
6.075       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6.075         File
6.075       "/root/.cache/uv/builds-v0/.tmpq7epIe/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py",
6.075       line 92, in build
6.075           self.metadata.validate_fields()
6.075         File
6.075       "/root/.cache/uv/builds-v0/.tmpq7epIe/lib/python3.11/site-packages/hatchling/metadata/core.py",
6.075       line 266, in validate_fields
6.075           self.core.validate_fields()
6.075         File
6.075       "/root/.cache/uv/builds-v0/.tmpq7epIe/lib/python3.11/site-packages/hatchling/metadata/core.py",
6.075       line 1366, in validate_fields
6.075           getattr(self, attribute)
6.075         File
6.075       "/root/.cache/uv/builds-v0/.tmpq7epIe/lib/python3.11/site-packages/hatchling/metadata/core.py",
6.075       line 700, in license
6.075           raise OSError(message)
6.075       OSError: License file does not exist: LICENSE
6.075
6.075       hint: This usually indicates a problem with the package or the build
6.075       environment.
------
Dockerfile:27
--------------------
  26 |     # Install dependencies and build the package
  27 | >>> RUN uv venv && \
  28 | >>>     uv pip install -e . && \
  29 | >>>     uv pip install --no-deps .
  30 |
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c uv venv &&     uv pip install -e . &&     uv pip install --no-deps ." did not complete successfully: exit code: 1

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>